# Using Python for Research Homework: Week 2

In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe (noughts and crosses) simulator and evaluate basic winning strategies.

### Exercise 1

Tic-tac-toe (or noughts and crosses) is a simple strategy game in which two players take turns placing a mark on a 3x3 board, attempting to make a row, column, or diagonal of three with their mark. In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe simulator and evaluate basic winning strategies.

In the following exercises, we will learn to create a tic-tac-toe board, place markers on the board, evaluate if either player has won, and use this to simulate two basic strategies.

#### Instructions 

- For our tic-tac-toe board, we will use a numpy array with dimension 3 by 3. 
- Make a function `create_board()` that creates such a board with the value of each cell set to the integer `0`.
- Call `create_board()` and store it.

In [1]:
import numpy as np

# Define the function to create a 3x3 tic-tac-toe board
def create_board():
    return np.zeros((3, 3), dtype=int)

# Call create_board() and store the result
board = create_board()

# Display the board
print("Tic-tac-toe board:")
print(board)



Tic-tac-toe board:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Exercise 2

Players 1 and 2 will take turns changing values of this array from a 0 to a 1 or 2, indicating the number of the player who places a marker there.

#### Instructions 

- Create a function `place(board, player, position)`, where:
    - `player` is the current player (an integer 1 or 2).
    - `position` is a tuple of length 2 specifying a desired location to place their marker.
    - Your function should only allow the current player to place a marker on the board (change the board position to their number) if that position is empty (zero).
- Use `create_board()` to store a board as `board`, and use `place` to have Player 1 place a marker on location `(0, 0)`.

In [2]:
import numpy as np

# Define the function to create a 3x3 tic-tac-toe board
def create_board():
    return np.zeros((3, 3), dtype=int)

# Define the place function
def place(board, player, position):
    # Check if the specified position is empty
    if board[position] == 0:
        board[position] = player
    else:
        print(f"Position {position} is already occupied.")

# Initialize the board and use place() to place a marker for Player 1 at (0, 0)
board = create_board()
place(board, 1, (0, 0))

# Display the board
print("Board after Player 1 places a marker at (0, 0):")
print(board)


Board after Player 1 places a marker at (0, 0):
[[1 0 0]
 [0 0 0]
 [0 0 0]]


### Exercise 3

In this exercise, we will determine which positions are available to either player for placing their marker.

#### Instructions 
- Create a function `possibilities(board)` that returns a list of all positions (tuples) on the board that are not occupied (0). (Hint: `numpy.where` is a handy function that returns a list of indices that meet a condition.)
- `board` is already defined from previous exercises. Call `possibilities(board)` to see what it returns!

In [3]:
import numpy as np

# Define the function to get a list of available positions on the board
def possibilities(board):
    # Find the indices where the board has value 0 (unoccupied positions)
    available_positions = np.where(board == 0)
    
    # Combine row and column indices into a list of tuples
    positions = list(zip(available_positions[0], available_positions[1]))
    
    return positions

# Example usage with the existing board from previous exercises
# Assuming `board` is defined and already has some positions marked
available_positions = possibilities(board)

# Display the available positions
print("Available positions on the board:", available_positions)


Available positions on the board: [(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]


### Exercise 4

The next step is for the current player to place a marker among the available positions. In this exercise, we will select an available board position at random and place a marker there.

#### Instructions 

- Write a function `random_place(board, player)` that places a marker for the current player at random among all the available positions (those currently set to 0).
    - Find possible placements with `possibilities(board)`.
    - Select one possible placement at random using `random.choice(selection)`.
- `board` is already defined from previous exercises. Call `random_place(board, player)` to place a random marker for Player 2, and store this as board to update its value.

In [5]:
import random

# Define the random_place function
def random_place(board, player):
    # Get the list of available positions
    available_positions = possibilities(board)
    
    # Select a random position from the available positions
    if available_positions:  # Check if there are available positions
        position = random.choice(available_positions)
        
        # Place the marker for the player at the selected position
        place(board, player, position)
    else:
        print("No available positions left.")

# Place a random marker for Player 2 on the board and update the board
random_place(board, 2)

# Display the board after the random placement
print("Board after Player 2 places a random marker:")
print(board)


Board after Player 2 places a random marker:
[[1 0 0]
 [2 0 0]
 [0 0 0]]


### Exercise 5

We will now have both players place three markers each.

#### Instructions 

- A new `board` is already given. Call `random_place(board, player)` to place three pieces each on board for players 1 and 2.
- Print board to see your result.

In [6]:
# Initialize a new board
board = create_board()

# Place three markers for each player
for _ in range(3):
    random_place(board, 1)  # Player 1
    random_place(board, 2)  # Player 2

# Display the board after both players have placed three markers
print("Board after each player places three markers:")
print(board)

Board after each player places three markers:
[[1 1 0]
 [0 0 2]
 [2 1 2]]


### Exercise 6

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Make a function `row_win(board, player)` that takes the player (integer) and determines if any row consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `row_win` to check if Player 1 has a complete row.

In [7]:
import numpy as np

# Define the row_win function
def row_win(board, player):
    # Check each row to see if it consists entirely of the player's markers
    for row in board:
        if np.all(row == player):  # np.all checks if all elements in the row are equal to player
            return True
    return False

# Example usage: Check if Player 1 has a winning row
has_row_win = row_win(board, 1)

# Print the result
print("Does Player 1 have a complete row?", has_row_win)


Does Player 1 have a complete row? False


### Exercise 7

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Make a function `col_win(board, player)` that takes the player (integer) and determines if any column consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `col_win` to check if Player 1 has a complete row.

In [8]:
import numpy as np

# Define the col_win function
def col_win(board, player):
    # Check each column to see if it consists entirely of the player's markers
    for col in range(board.shape[1]):  # board.shape[1] gives the number of columns
        if np.all(board[:, col] == player):  # Check if all elements in the column are equal to player
            return True
    return False

# Example usage: Check if Player 1 has a winning column
has_col_win = col_win(board, 1)

# Print the result
print("Does Player 1 have a complete column?", has_col_win)

Does Player 1 have a complete column? False


### Exercise 8

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Finally, create a function `diag_win(board, player)` that tests if either diagonal of the board consists of only their marker. Have it return `True` if this condition is met, and `False` otherwise.
- `board` has been slightly modified from a previous exercise. Call `diag_win` to check if Player 2 has a complete diagonal.

In [9]:
import numpy as np

# Define the diag_win function
def diag_win(board, player):
    # Check the main diagonal (from top-left to bottom-right)
    if np.all(np.diag(board) == player):
        return True
    
    # Check the anti-diagonal (from top-right to bottom-left)
    if np.all(np.diag(np.fliplr(board)) == player):
        return True
    
    # Return False if neither diagonal is fully occupied by the player's marker
    return False

# Example usage: Check if Player 2 has a winning diagonal
has_diag_win = diag_win(board, 2)

# Print the result
print("Does Player 2 have a complete diagonal?", has_diag_win)


Does Player 2 have a complete diagonal? False


### Exercise 9

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Create a function `evaluate(board)` that uses `row_win`, `col_win`, and `diag_win` functions for both players. If one of them has won, return that player's number. If the board is full but no one has won, return -1. Otherwise, return 0.
- `board` is already defined from previous exercises. Call evaluate to see if either player has won the game yet.

In [10]:
import numpy as np

# Define the evaluate function
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        # Check if the player has won in any row, column, or diagonal
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
            break  # Exit the loop if a winner is found

    # Check if the board is full and no winner has been found
    if np.all(board != 0) and winner == 0:
        winner = -1

    return winner

# Example usage: Check if either player has won or if it's a draw
game_status = evaluate(board)

# Print the result
print("Game status:", game_status)


Game status: 0


### Exercise 10

In this exercise, we will use all the functions we have made to simulate an entire game.

#### Instructions 

- `create_board()`, `random_place(board, player)`, and `evaluate(board)` have been created in previous exercises. Create a function `play_game()` that:
    - Creates a board.
    - Alternates taking turns between two players (beginning with Player 1), placing a marker during each turn.
    - Evaluates the board for a winner after each placement.
    - Continues the game until one player wins (returning 1 or 2 to reflect the winning player), or the game is a draw (returning -1).
- Call play_game 1000 times, and store the results of the game in a list called `results`.

In [11]:
import numpy as np
import random

# Define the play_game function
def play_game():
    # Create a new tic-tac-toe board
    board = create_board()
    
    # Initialize variables for alternating turns
    current_player = 1
    
    # Continue playing until there's a winner or a draw
    while True:
        # Place a marker for the current player at a random position
        random_place(board, current_player)
        
        # Evaluate the board to see if there's a winner or a draw
        result = evaluate(board)
        
        # If there's a result (win or draw), return it
        if result != 0:
            return result
        
        # Switch to the other player
        current_player = 2 if current_player == 1 else 1

# Simulate 1000 games and store the results
results = [play_game() for _ in range(1000)]

# Display the results
print("Game results over 1000 simulations:", results)


Game results over 1000 simulations: [2, 1, 2, -1, -1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, -1, 1, 1, 2, 1, 1, -1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, -1, 2, 1, 2, 1, -1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, -1, 1, 1, 2, 2, -1, 1, -1, 2, 1, -1, 1, 1, 2, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, -1, 1, 1, 1, 2, 1, 1, 1, 1, -1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, -1, 1, 1, 2, 1, 2, 2, 2, -1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 2, 2, 1, 1, -1, 1, -1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 2, 1, -1, -1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 2, -1, 2, 1, 2, 1, -1, 1, -1, 2, 1, 2, 2, 1, 2, 1, 2, 1, -1, 2, 2, 1, 1, 1, -1, 1, 2, 1, 1, 1, 1, 2, 1, 1, -1, -1, 1, 2, 2, 2, 1, 1, 1, -1, 1, 2, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, -1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, -1, 1

#### Exercise 11

In the previous exercise, we see that when guessing at random, it's better to go first, as expected. Let's see if Player 1 can improve their strategy. 

#### Instructions 
- Create a function `play_strategic_game()`, where Player 1 always starts with the middle square, and otherwise both players place their markers randomly.
- Call `play_strategic_game` 1000 times.

In [12]:
import numpy as np
import random

# Define the play_strategic_game function
def play_strategic_game():
    # Create a new tic-tac-toe board
    board = create_board()
    
    # Player 1 starts with the middle square
    board[1, 1] = 1
    
    # Initialize the current player (starting with Player 2 after Player 1's strategic move)
    current_player = 2
    
    # Continue playing until there's a winner or a draw
    while True:
        # Player 1 has already taken the center spot, so continue with random placements
        random_place(board, current_player)
        
        # Evaluate the board to see if there's a winner or a draw
        result = evaluate(board)
        
        # If there's a result (win or draw), return it
        if result != 0:
            return result
        
        # Switch to the other player
        current_player = 2 if current_player == 1 else 1

# Simulate 1000 games using the strategic starting move for Player 1
strategic_results = [play_strategic_game() for _ in range(1000)]

# Display the results
print("Game results over 1000 strategic simulations:", strategic_results)


Game results over 1000 strategic simulations: [1, 1, -1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, -1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, -1, 1, -1, 1, 1, 1, 2, 1, 1, -1, 1, 2, -1, -1, 1, 2, -1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, 1, -1, 2, 1, 1, 2, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 2, 1, 1, 1, 1, 1, 2, 1, 1, -1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, -1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, -1, 2, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 2, 1, -1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 2, 1, 1, 1, 1, 1, 2, 1, 1, -1, 1, 1, 1, 1, 2, 1, 1, -1, 1, 1, 1, 1, 2, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 2, -1, -1, 2, 2, 2, 2, 1, -1, 1, -1, 1, 1, 1, 2, -1, 1, 1, 1, 1, -1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, -1, 1, -1, 2, 1, 1, 1, -1, 2, 1, 1, 1, 1, 2, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1